name: Generar y Publicar Nuevo Post

on:
  # Permite ejecutarlo manualmente desde la pestaña Actions en GitHub
  workflow_dispatch:

  # Ejecuta el script automáticamente en un horario programado
  schedule:
    # Esta configuración ejecuta el script cada 6 horas (4 veces al día)
    - cron: '0 */6 * * *'

# Permisos necesarios para que la acción pueda escribir en tu repositorio
permissions:
  contents: write

jobs:
  build-and-commit:
    # Se ejecutará en un servidor de Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repositorio para tener acceso a los archivos
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python en la versión 3.10
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala las librerías necesarias desde tu archivo requirements.txt
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecuta el script de Python para generar el contenido
      #    Usa un "secret" de GitHub para la API Key, ¡nunca la pongas directamente!
      - name: Generar nuevo post
        run: python generar_post.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      # 5. Configura Git y sube los nuevos archivos generados al repositorio
      - name: Hacer commit de los archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensaje del commit que aparecerá en tu historial de Git
          commit_message: "🤖 Nuevo post automatizado"
