name: Generar y Publicar Nuevo Post

on:
  workflow_dispatch:
  schedule:
    # Ejecuta el script automáticamente cada 4 horas
    - cron: '0 */4 * * *'

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generar nuevo post
        run: python generar_post.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Hacer commit de los archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Nuevo post automatizado"
